---
- name: 🚀 Deploy WordPress to ECS Fargate
  hosts: ecs_servers
  gather_facts: false
  serial: 1

  vars_files:
    - vars/wordpress.yml

  roles:
    - role: wordpress
      tags: wordpress

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"

  tasks:
    - name: Display deployment information
      debug:
        msg: |
          Starting WordPress ECS Deployment
          =================================
          Environment: {{ environment }}
          Region: {{ aws_region }}
          Cluster: {{ ecs_cluster }}
          Service: {{ ecs_service }}
          Task Family: {{ ecs_task_family }}
          DB Host: {{ db_host }}