---
- name: ✅ WordPress Health Check
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get ALB DNS name
      shell: |
        aws elbv2 describe-load-balancers \
          --names wordpress-alb-dev \
          --region eu-north-1 \
          --query 'LoadBalancers[0].DNSName' \
          --output text
      register: alb_dns

    - name: Check WordPress health
      uri:
        url: "http://{{ alb_dns.stdout }}/wp-admin/install.php"
        method: GET
        timeout: 30
        status_code: 200, 302
      register: health_check

    - name: Show health status
      debug:
        msg: |
          WordPress Health Check: 
          URL: http://{{ alb_dns.stdout }}
          Status: {{ health_check.status }}
          Response: {{ 'HEALTHY' if health_check.status in [200, 302] else 'UNHEALTHY' }}
