---
- name: 🔄 Rollback WordPress Deployment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get previous task definition
      shell: |
        aws ecs describe-task-definition \
          --task-definition {{ ecs_task_family }} \
          --region {{ aws_region }} \
          --query 'taskDefinition.revision' \
          --output text
      register: current_revision

    - name: Calculate previous revision
      set_fact:
        previous_revision: "{{ current_revision.stdout | int - 1 }}"

    - name: Rollback to previous version
      amazon.aws.ecs_service:
        state: present
        name: "{{ ecs_service }}"
        cluster: "{{ ecs_cluster }}"
        task_definition: "{{ ecs_task_family }}:{{ previous_revision }}"
        region: "{{ aws_region }}"

    - name: Confirm rollback
      debug:
        msg: "✅ Rolled back to revision {{ previous_revision }}"
