---
- name: Deploy WordPress task definition
  amazon.aws.ecs_taskdefinition:
    state: present
    family: "{{ ecs_task_family }}"
    network_mode: awsvpc
    requires_compatibilities: 
      - FARGATE
    cpu: 1024
    memory: 2048
    container_definitions: |
      [
        {
          "name": "wordpress",
          "image": "{{ docker_image }}",
          "essential": true,
          "portMappings": [
            {
              "containerPort": 80,
              "hostPort": 80,
              "protocol": "tcp"
            }
          ],
          "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
              "awslogs-group": "{{ cloudwatch_log_group }}",
              "awslogs-region": "{{ aws_region }}",
              "awslogs-stream-prefix": "ecs"
            }
          }
        }
      ]
    region: "{{ aws_region }}"
  register: task_def

- name: Update ECS service
  amazon.aws.ecs_service:
    state: present
    name: "{{ ecs_service }}"
    cluster: "{{ ecs_cluster }}"
    task_definition: "{{ task_def.taskdefinition.taskDefinitionArn }}"
    desired_count: 1
    launch_type: FARGATE
    region: "{{ aws_region }}"
